# Generated by Django 5.0.3 on 2025-01-25 16:00

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0002_alter_client_phone_number_alter_client_zipcode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="phone_number",
            field=models.CharField(
                default=9999999999,
                max_length=20,
                validators=[core.validators.validate_phone_number],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contact",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contacts",
                to="registry.client",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone_number",
            field=models.CharField(
                default=9999999999,
                max_length=20,
                validators=[core.validators.validate_phone_number],
            ),
            preserve_default=False,
        ),
    ]
